#!/bin/bash
echo "Cleanup old files..."
cd /opt/docker/digi/conf/tnn
rm -rf *
cd ..
cd /opt/docker/digi/conf/openbcm
rm -rf *
echo "Cleanup Docker..."
docker container rm -f digi_tnn_1
docker container rm -f digi_openbcm_1
docker image rm -f digi_tnn
docker image rm -f digi_openbcm
#docker image rm -f debian
docker system prune
cd /opt/docker/digi
echo "Finished!"
echo "To build enter y to prompt:"
read -r ans
if [ "$ans" == "y" ]; then
   docker-compose up -d
   echo "To connect to containers, type..."
   echo "TNN: docker exec -i -t digi_tnn_1 /bin/bash"
   echo "OpenBCM: docker exec -i -t digi_openbcm_1 /bin/bash"
fi
