#!/bin/bash
echo "Cleanup old files..."
cd /opt/docker/digi/tnn179mh06/
rm -rf ax25ip.cfg parms.tnb tnn179.pas tnn179.tnb tnn.ini
cd ..
cd /opt/docker/digi/openbcm1.07b12/
rm -rf bidh2.bcm  bids3.bcm bulletin.bak bulletin.bcm core.6 crontab.bcm fwd fwd.bcm hadr4.bcm hadrhash.bcm http info init.bcm init.l2 log msg speech.bcm trace user userh2.bcm users4.bak users4.bcm
echo "Cleanup Docker..."
docker container rm -f digi_tnn_1
docker container rm -f digi_openbcm_1
docker image rm -f digi_tnn
docker image rm -f digi_openbcm
docker image rm -f debian
docker system prune
cd /opt/docker/digi
echo "Finished!"
echo "To build enter y to prompt:"
read -r ans
if [ "$ans" == "y" ]; then
   docker-compose up -d
   echo "TNN: docker exec -i -t digi_tnn_1 /bin/bash"
   echo "BCM: docker exec -i -t digi_bcm_1 /bin/bash"
fi
