version: '3'
services:
  tnn:
    build:
     context: ./tnn179mh06/
     args:
      pwsysop: 12345678901234567890123456789012345678901234567890123456789012345678901234567890
      pwconsole: geheimespw
      nodeident: Test
      nodecall: DL1NE
      port1: 9k6_User|/dev/ttyS0|1|9600
      port15: AX25IP|AX25IP|8|19200d
    ports:
     - 10093:10093/udp
    volumes:
     - ./conf/tnn/:/cfg
    devices:
     - /dev/ttyS0:/dev/ttyS0
    restart: unless-stopped
  openbcm:
    build:
     context: ./openbcm1.07b12/
     args:
      boxaddr: DL1NE.#NDS.DEU.EU
      mycall: DL1NE
      sysop: DL1NE
    ports:
     - 8081:8080
     - 8025:8025
     - 8110:8110
     - 8119:8119
    volumes:
     - ./conf/openbcm/:/cfg
