#!/bin/bash
TNNPATH=/usr/local/tnn

echo "Setting up Ports of TNN..."
echo >> $TNNPATH/tnn.ini
echo >> $TNNPATH/tnn.ini
echo "# -----------------------------------------------------" >> $TNNPATH/tnn.ini
echo "# Ports created with util wizard_ports, during build" >> $TNNPATH/tnn.ini
echo "# -----------------------------------------------------" >> $TNNPATH/tnn.ini
i=0
axipport=-1
for var in "$@"
do
    i=$((i+1))
    if [ "$var" != "" ]; then
	echo "Port $i: $var"
	pname=`echo "$var" | cut -d '|' -f1`
	device=`echo "$var" | cut -d '|' -f2`
	kiss=`echo "$var" | cut -d '|' -f3`
	speed=`echo "$var" | cut -d '|' -f4`
	lock=`echo "$var" | cut -d '|' -f5`
	if [ $kiss -eq 8 ]; then
		axipport=$i
	fi
	echo "#" >> $TNNPATH/tnn.ini
	echo "# Port $i" >> $TNNPATH/tnn.ini
	echo "device $device" >> $TNNPATH/tnn.ini
	echo "kisstype $kiss" >> $TNNPATH/tnn.ini
	echo "port $i" >> $TNNPATH/tnn.ini
	if [ "$speed" != "" ]; then
		echo "speed $speed" >> $TNNPATH/tnn.ini
	else
		speed=1200
	fi
	if [ "$lock" != "" ]; then
		echo "tnn_lockfile $lock" >> $TNNPATH/tnn.ini
	fi
	sed -i "s/port\s\+$i NAME.*/port $i NAME=$pname ON MODE=$speed MH=1/g" $TNNPATH/tnn179.tnb
        cat $TNNPATH/tnn179.tnb | grep "port $i"
    fi
done
echo
echo 
if [ $axipport -ne -1 ]; then
	echo "Setting up AX25IP..."
	sed -i "s/socket ip/# socket ip/g" $TNNPATH/ax25ip.cfg
	sed -i "s/#socket udp 10093/socket udp 10093/g" $TNNPATH/ax25ip.cfg
	sed -i "s/^route/#route/g" $TNNPATH/ax25ip.cfg
	sed -i "s/#route default.*/route default 44.225.65.146 udp 10093/g" $TNNPATH/ax25ip.cfg
	echo "route db0luh 44.225.65.146 udp 10093" >> $TNNPATH/ax25ip.cfg
	echo "route db0ner 44.225.65.194 udp 10093" >> $TNNPATH/ax25ip.cfg
	echo "route db0uhi 44.225.64.194 udp 10092" >> $TNNPATH/ax25ip.cfg
	echo "route dk0mav 44.225.94.130 udp 10092" >> $TNNPATH/ax25ip.cfg
	echo
	echo
	echo "Setting up OpenBCM Link..."
	echo "LINK + L  15 ${nodeident} ${nodecall}-4" >> $TNNPATH/tnn179.tnb
	echo "MAILBOX ${nodecall}-4" >> $TNNPATH/tnn179.tnb
	echo "route ${nodecall}-4 openbcm udp 10091" >> $TNNPATH/ax25ip.cfg
	echo
	echo
fi
echo
echo
echo "Your tnn179.tnb:"
cat $TNNPATH/tnn179.tnb
echo
echo
echo "Setting up some other defaults..."
#
# ctext.txt
#
if [ ! -f $TNNPATH/ctext.txt ]; then
    echo "*****************************************************************" > $TNNPATH/ctext.txt
    echo "* Digipeater: ${nodecall}                        ${location}" >> $TNNPATH/ctext.txt
    echo "* Locator   : ${locator}" >> $TNNPATH/ctext.txt
    echo "*" >> $TNNPATH/ctext.txt
    echo "*   (A)ktuell: %A       (I)nfo      (M)ailbox = ${nodecall}-4" >> $TNNPATH/ctext.txt
    echo "*   (U)ser                    (Q)uit      (N)odes" >> $TNNPATH/ctext.txt
    echo "*   (CONV)ers                 (H)ilfe     (MH)eard" >> $TNNPATH/ctext.txt
    echo "*" >> $TNNPATH/ctext.txt
    echo "*****************************************************************" >> $TNNPATH/ctext.txt
    echo "* This Digi based on Docker: https://github.com/dl1ne/docker-digi" >> $TNNPATH/ctext.txt
    echo "* created by HamNET Group AS64636, DL1NE" >> $TNNPATH/ctext.txt
    echo "*****************************************************************" >> $TNNPATH/ctext.txt
fi
#
# aktuell.txt
#
if [ ! -f $TNNPATH/textcmd/aktuell.txt ]; then
    echo " 03.07.2018, DL1NE" > $TNNPATH/textcmd/aktuell.txt
    echo "=============================================" >> $TNNPATH/textcmd/aktuell.txt
    echo " Docker Images sind soweit lauffaehig," >> $TNNPATH/textcmd/aktuell.txt
    echo " eine Verbindung mit OpenBCM unter -4 " >> $TNNPATH/textcmd/aktuell.txt
    echo " ist ebenso moeglich." >> $TNNPATH/textcmd/aktuell.txt
fi
#
# info.txt
#
if [ ! -f $TNNPATH/textcmd/info.txt ]; then
    echo "TheNetNode Digi basierend auf Docker Images :-)" > $TNNPATH/textcmd/info.txt
fi
